package CCCU.edu.hk.GUI;

import CCCU.edu.hk.Scholarships.External_Scholarships;
import CCCU.edu.hk.Scholarships.Internal_Scholarships;
import CCCU.edu.hk.Scholarships.Scholarships;
import CCCU.edu.hk.ScholarshipsDB.ScholarshipsDB;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cheng
 */
public class detailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form detailsFrame
     */
    private String print;
    private String print2;
    //private ScholarshipsDB scholarshipsDB;
    //private Scholarships scholarships; 
    private Internal_Scholarships internal;
    private External_Scholarships external;
    
    public detailsFrame(Internal_Scholarships internalPass) {
        print = "";
        print2 = "";
        internal = internalPass;
        print = "Name:"+internal.getName()+"\nOrganisation:"+internal.getOrganisation()+"\nDescription:"+internal.getDescription()+"\nDue date:" + internal.getInitialCutOff().toString()+"\nFinal CutOff Date"+internal.getFinalCutOff().toString()+"\nMax Awardees:" + internal.getMaxAwardees()+"\nMax Applicants:"+internal.getMaxApplicants()+"\nAmount:"+internal.getAmount();
        print2 ="Early CutOff Date"+internal.getInitialCutOff().toString()+"\nFinal CutOff" + internal.getFinalCutOff().toString()+"\nCGPA Requirements:"+internal.getCGPA();
        initComponents();
    }

    public detailsFrame(External_Scholarships externalPass){
        print = "";
        print2= "";
        external = externalPass;
        print = "Name:"+external.getName()+"\nOrganisation:"+external.getOrganisation()+"\nDescription:"+external.getDescription()+"\nDue date:" + external.getInitialCutOff().toString()+"\nFinal CutOff Date"+external.getFinalCutOff().toString()+"\nMax Awardees:" + external.getMaxAwardees()+"\nMax Applicants:"+external.getMaxApplicants()+"\nAmount:"+external.getAmount();
        print2 ="Early CutOff Date"+external.getInitialCutOff().toString()+"\nFinal CutOff" + external.getFinalCutOff().toString()+"\nCGPA Requirements:"+external.getCGPA();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel2.setText("Requirements");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = print.split("\n");
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = print2.split("\n");
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
